name: Supabase Activity Scheduler

on:
  schedule:
    - cron: '0 15 * * *'  # 毎日15:00（日本時間、JST）に実行
  workflow_dispatch:

jobs:
  prevent_pause:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}  # SupabaseプロジェクトURL
      SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}  # Supabase Anon Key
    steps:
      - name: Send HTTP Request to Supabase
        run: |
          curl -X GET "${SUPABASE_URL}/rest/v1/clock_items?select=*" \
          -H "Authorization: Bearer ${SUPABASE_KEY}" \
          -H "apikey: ${SUPABASE_KEY}"
